
--有参数函数
SELECT MAX(TAGE) FROM TEACHER

--无参数函数
SELECT GETDATE()
SELECT 3*5
--COUNT函数

SELECT * FROM STUDENT
SELECT COUNT(*) FROM STUDENT
SELECT COUNT(SDEPT) FROM STUDENT
SELECT COUNT(DISTINCT SDEPT) FROM STUDENT
--AVG函数
SELECT SUM(SAGE)/COUNT(*) FROM STUDENT

SELECT SUM(SAGE)/COUNT(SAGE) FROM STUDENT

SELECT AVG(SAGE) FROM STUDENT

SELECT SDEPT,AVG(SAGE) FROM STUDENT--出错
--分组汇总
SELECT SDEPT,AVG(SAGE) 
FROM STUDENT
GROUP BY SDEPT

SELECT SDEPT,SMAJOR,AVG(SAGE) 
FROM STUDENT
GROUP BY SDEPT--错误

SELECT SDEPT,COUNT(SMAJOR),AVG(SAGE) 
FROM STUDENT
GROUP BY SDEPT

SELECT SDEPT,AVG(SAGE) 
FROM STUDENT
GROUP BY SMAJOR,SDEPT

SELECT SDEPT,SMAJOR,AVG(SAGE) 
FROM STUDENT
GROUP BY SMAJOR,SDEPT

SELECT * FROM STUDENT
ORDER BY SMAJOR,SDEPT

SELECT SDEPT,SMAJOR,AVG(SAGE) 
FROM STUDENT
GROUP BY SMAJOR,SDEPT

--如果查询语句中有GROUP BY，则SELECT后面直接出现
--的属性只能是GROUP BY后面出现过的属性

--HAVING 
SELECT SDEPT,AVG(SAGE) 
FROM STUDENT
GROUP BY SDEPT
HAVING AVG(SAGE)>20

SELECT SDEPT,AVG(SAGE) 平均年龄,MAX(SAGE) 最大年龄
FROM STUDENT
WHERE SSEX='男'
GROUP BY SDEPT
HAVING MAX(SAGE)>24
ORDER BY MAX(SAGE) DESC


SELECT SDEPT,AVG(SAGE) 平均年龄,MAX(SAGE) 最大年龄
FROM STUDENT
WHERE SSEX='男'
GROUP BY SDEPT
HAVING 最大年龄>24
ORDER BY MAX(SAGE) DESC --错误

SELECT SDEPT,AVG(SAGE) 平均年龄,MAX(SAGE) 最大年龄
FROM STUDENT
WHERE SSEX='男'
GROUP BY SDEPT
HAVING MAX(SAGE)>24
ORDER BY 最大年龄 DESC

SELECT SDEPT,AVG(SAGE) 平均年龄,MAX(SAGE) 最大年龄
FROM STUDENT
WHERE MAX(SAGE)>5
GROUP BY SDEPT
HAVING MAX(SAGE)>24
ORDER BY 最大年龄 DESC  --错误，聚合不应出现在 WHERE 子句中

SELECT SDEPT,AVG(SAGE) 平均年龄,MAX(SAGE) 最大年龄
FROM STUDENT
WHERE SSEX='男'
GROUP BY SDEPT
HAVING SAGE>24
ORDER BY 最大年龄 DESC  --HAVING后面直接参与比较的属性必须出现在GROUP BY 后面

SELECT SDEPT,AVG(SAGE) 平均年龄,MAX(SAGE) 最大年龄
FROM STUDENT
WHERE SSEX='男'
GROUP BY SDEPT
HAVING SDEPT='计算机科学学院'
ORDER BY 最大年龄 DESC  