--查找所有的教师信息
SELECT * FROM TEACHER

--查找所有教师的教师号，教师名，院系
SELECT TNO,TNAME,TDEPT FROM TEACHER
SELECT TNAME,TNO,TDEPT FROM TEACHER
--修改列名
SELECT TNO 教工号,TNAME  教师名,TDEPT 院系 
FROM TEACHER
--计算
SELECT TNO 教工号,TNAME  教师名,60-TAGE  离退休年限
FROM TEACHER
--列组合
SELECT REPLACE (TNAME,' ','')+'还有'+convert(VARCHAR(2),(60-TAGE))+'年退休'
FROM TEACHER

--添加列
SELECT TNO 教工号,TNAME  教师名,'的院系是' aaa,TDEPT 院系 
FROM TEACHER

--查哪些院系有老师
SELECT DISTINCT TDEPT 院系 FROM TEACHER

--排序
SELECT * FROM TEACHER ORDER BY TAGE DESC
SELECT * FROM TEACHER ORDER BY TAGE 
SELECT * FROM TEACHER 
ORDER BY TDEPT ASC,TAGE DESC

--查前N行数据
SELECT TOP 3 * FROM TEACHER
SELECT TOP 1 * FROM TEACHER
ORDER BY TAGE DESC

--使用函数
SELECT AVG(TAGE) 平均年龄 FROM TEACHER

--查年龄小于40岁的教师
SELECT * FROM TEACHER WHERE TAGE<=40
--查年龄不等于39岁的教师
SELECT * FROM TEACHER WHERE TAGE<>39
--查年龄40到45岁的教师
SELECT * FROM TEACHER WHERE TAGE>=40 AND TAGE<=45
SELECT * FROM TEACHER WHERE TAGE BETWEEN 40 AND 45
--查年龄不在40到45岁的教师
SELECT * FROM TEACHER WHERE TAGE<40 OR TAGE>45
SELECT * FROM TEACHER WHERE NOT (TAGE>=40 AND TAGE<=45)
SELECT * FROM TEACHER WHERE TAGE NOT BETWEEN 40 AND 45

--复合条件
SELECT * FROM TEACHER 
WHERE (TAGE  NOT BETWEEN 40 AND 45) AND  TSEX='男'
--其他条件
SELECT * FROM TEACHER WHERE 1=2

--查姓刘的教师
SELECT * FROM TEACHER WHERE TNAME LIKE '刘%'

--查姓名两个字的教师
SELECT * FROM TEACHER WHERE TNAME LIKE '__'

--查姓名含山的教师
SELECT * FROM TEACHER WHERE TNAME LIKE '%山%'

--查姓邮箱号含N的教师
SELECT * FROM TEACHER WHERE EMAIL LIKE '%N%@%'  

--查姓邮箱号含N或Z的教师
SELECT * FROM TEACHER WHERE EMAIL  LIKE '%[NZ]%@%'  

--查姓邮箱号不含N或Z的教师
SELECT * FROM TEACHER WHERE EMAIL  LIKE '%[^NZ]%@%'  --错
SELECT * FROM TEACHER WHERE EMAIL NOT  LIKE '%[^NZ]%@%' 
SELECT * FROM TEACHER WHERE EMAIL  LIKE '%[^NZ]I%@%'  
SELECT * FROM TEACHER WHERE EMAIL  LIKE '[^ZL]%@%'  
--查找含有特殊符号的
SELECT * FROM TEACHER WHERE TNAME='%'
SELECT * FROM TEACHER 
WHERE TNAME  LIKE '%#%%' ESCAPE '#'

--查职称为空值的教师
SELECT * FROM TEACHER WHERE TPROT IS NULL

--查职称为空值的教师
SELECT * FROM TEACHER WHERE TPROT  IS NOT NULL
SELECT * FROM TEACHER WHERE TPROT NOT  IS  NULL--错误
SELECT * FROM TEACHER WHERE NOT TPROT  IS  NULL
